apiVersion: v1
kind: ConfigMap
metadata:
  name: locatic-config
  namespace: locatic
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"
  DB_PATH: "Data Source=/app/data/locatic.db"