apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: locatic-sqlite-pvc
  namespace: locatic
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
  volumeName: locatic-sqlite-pv